AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Resources for Lambda function to update SSM Parameter

Resources:
  ImageBuilderSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "Image Builder"

  UpdateSSMParameter:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: image-builder-lambda-update-ssm.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: Update SSM Parameter with the latest AMI
      MemorySize: 256
      Timeout: 300
      AutoPublishAlias: live
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref ImageBuilderSNSTopic
      Policies:
          - arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:AddTagsToResource
                  - ssm:GetParameters
                Resource: '*'

Outputs:
  LambdaArn:
    Description: Lambda Function Arn
    Value: !GetAtt UpdateSSMParameter.Arn
    Export:
      Name: image-builder-lambda-update-ssm-arn

  SNSTopicArn:
    Description: SNS Topic Arn
    Value: !Ref ImageBuilderSNSTopic
    Export:
      Name: image-builder-lambda-sns-arn



