# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
name: Ansible Playbook Execution on Amazon Linux 2
description: This is a sample component that demonstrates how to download and execute an Ansible playbook against Amazon Linux 2.
schemaVersion: 1.0
phases:
  - name: build
    steps:
      - name: InstallAnsible
        action: ExecuteBash
        inputs:
          commands:
            - |
              if [ -x "$(command -v ansible-playbook)" ]; then
                echo "Ansible is already installed."
              else
                echo "Installing Ansible..."
                sudo amazon-linux-extras install -y ansible2
              fi
      - name: DownloadPlaybook
        action: S3Download
        inputs:
          - source: s3://<enter_s3_bucket_name_here>/<enter_s3_object_key_here>
            destination: /tmp/playbook.yml
      - name: InvokeAnsible
        action: ExecuteBinary
        inputs:
          path: ansible-playbook
          arguments:
            - '{{ build.DownloadPlaybook.inputs[0].destination }}'
      - name: DeletePlaybook
        action: ExecuteBash
        inputs:
          commands:
            - rm {{ build.DownloadPlaybook.inputs[0].destination }}
